# Generated by Django 4.2 on 2023-04-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=200)),
                ("image", models.ImageField(upload_to="blog/")),
                ("title1", models.CharField(max_length=100)),
                ("long_description1", models.TextField()),
                ("title2", models.CharField(blank=True, max_length=100)),
                ("long_description2", models.TextField(blank=True)),
            ],
        ),
    ]
