# Generated by Django 4.2 on 2023-04-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aaj_ka_Rashifal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Aries", models.TextField()),
                ("Taurus", models.TextField()),
                ("Gemini", models.TextField()),
                ("Cancer", models.TextField()),
                ("Leo", models.TextField()),
                ("Virgo", models.TextField()),
                ("Libra", models.TextField()),
                ("Scorpio", models.TextField()),
                ("Sagittarius", models.TextField()),
                ("Capricorn", models.TextField()),
                ("Aquarius", models.TextField()),
                ("Pisces", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="AboutGuruji",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="about/")),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("address", models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="BannerImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banner_description", models.TextField(max_length=255)),
                (
                    "banner_background",
                    models.ImageField(blank=True, upload_to="banners/"),
                ),
                ("banner_image", models.ImageField(upload_to="banners/")),
            ],
        ),
        migrations.CreateModel(
            name="Festival",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("january", models.TextField()),
                ("february", models.TextField()),
                ("march", models.TextField()),
                ("april", models.TextField()),
                ("may", models.TextField()),
                ("june", models.TextField()),
                ("july", models.TextField()),
                ("august", models.TextField()),
                ("september", models.TextField()),
                ("october", models.TextField()),
                ("november", models.TextField()),
                ("december", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_no", models.CharField(max_length=12)),
                ("email_id", models.EmailField(max_length=254)),
                ("Address", models.TextField(max_length=255)),
                ("facebook", models.CharField(max_length=255)),
                ("instagram", models.CharField(blank=True, max_length=255, null=True)),
                ("twitter", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GurujiWords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="guruji_words/")),
                ("heading", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Our_Services_Cards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="our_services_cards/")),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ResolveProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="resolve_problem/")),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="testimonial/")),
                ("description", models.TextField()),
                ("name", models.CharField(max_length=255)),
                ("designation", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial_status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Happy_Clients", models.IntegerField()),
                ("Services_Available", models.IntegerField()),
                ("Happy_Family", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Todays_Updates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nakshatra", models.CharField(max_length=150)),
                ("image", models.ImageField(upload_to="todays_updates/")),
                ("tithi", models.CharField(max_length=150)),
                ("sunrise", models.CharField(max_length=150)),
                ("sunset", models.CharField(max_length=150)),
                ("yoga", models.CharField(max_length=150)),
                ("rashi", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("todays_update", models.TextField()),
                (
                    "short_description",
                    models.TextField(default="guruji", max_length=50),
                ),
            ],
        ),
    ]
