# Generated by Django 4.2 on 2023-04-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gorchar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="second_top_image/")),
                ("title1", models.CharField(max_length=100)),
                ("description1", models.TextField()),
                ("title2", models.CharField(max_length=100)),
                ("description2", models.TextField()),
                ("title3", models.CharField(max_length=100)),
                ("description3", models.TextField()),
                ("title4", models.CharField(max_length=100)),
                ("description4", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Guruji",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="about/")),
                ("image2", models.ImageField(upload_to="about/")),
                ("image3", models.ImageField(upload_to="about/")),
                ("image4", models.ImageField(upload_to="about/")),
                ("image5", models.ImageField(upload_to="about/")),
                ("image6", models.ImageField(upload_to="about/")),
                ("meet_guruji_image", models.ImageField(upload_to="meet_guruji/")),
                ("date1", models.DateField()),
                ("location1", models.URLField()),
                ("meet_guruji_image2", models.ImageField(upload_to="meet_guruji/")),
                ("date2", models.DateField()),
                ("location2", models.URLField()),
                ("meet_guruji_image3", models.ImageField(upload_to="meet_guruji/")),
                ("date3", models.DateField()),
                ("location3", models.URLField()),
                ("book_image", models.ImageField(upload_to="book_images/")),
                ("book_url", models.URLField()),
                ("book_image2", models.ImageField(upload_to="book_images/")),
                ("book2_url", models.URLField()),
                ("book_image3", models.ImageField(upload_to="book_images/")),
                ("book3_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Horoscope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="second_top_image/")),
                ("title1", models.CharField(max_length=100)),
                ("description1", models.TextField()),
                ("title2", models.CharField(max_length=100)),
                ("description2", models.TextField()),
                ("title3", models.CharField(max_length=100)),
                ("description3", models.TextField()),
                ("title4", models.CharField(max_length=100)),
                ("description4", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Kundli",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="second_top_image/")),
                ("title1", models.CharField(max_length=100)),
                ("description1", models.TextField()),
                ("title2", models.CharField(max_length=100)),
                ("description2", models.TextField()),
                ("title3", models.CharField(max_length=100)),
                ("description3", models.TextField()),
                ("title4", models.CharField(max_length=100)),
                ("description4", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Vedic_astrology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="second_top_image/")),
                ("title1", models.CharField(max_length=100)),
                ("description1", models.TextField()),
                ("title2", models.CharField(max_length=100)),
                ("description2", models.TextField()),
                ("title3", models.CharField(max_length=100)),
                ("description3", models.TextField()),
                ("title4", models.CharField(max_length=100)),
                ("description4", models.TextField()),
            ],
        ),
    ]
